// services/exportService.ts
import { Dream } from '../types';

/**
 * Generates a printable HTML document for dream journal export
 */
const generatePrintableHTML = (dreams: Dream[]): string => {
    const dreamEntries = dreams.map(dream => {
        const date = new Date(dream.timestamp).toLocaleDateString('en-US', {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric'
        });

        const qualityStars = dream.sleepQuality
            ? '★'.repeat(dream.sleepQuality) + '☆'.repeat(5 - dream.sleepQuality)
            : 'Not rated';

        const tags = dream.tags?.length
            ? dream.tags.map(t => `#${t}`).join(' ')
            : '';

        const analysis = dream.aiAnalysis?.analysis
            .map(a => `<h4>${a.title}</h4><p>${a.content}</p>`)
            .join('') || '';

        return `
            <div class="dream-entry">
                <div class="dream-header">
                    <h2>${dream.title || 'Untitled Dream'}</h2>
                    <p class="date">${date}</p>
                    <p class="quality">Sleep Quality: ${qualityStars}</p>
                    ${tags ? `<p class="tags">${tags}</p>` : ''}
                </div>
                <div class="dream-content">
                    <h3>Dream</h3>
                    <p>${dream.dreamText}</p>
                </div>
                ${analysis ? `
                    <div class="dream-analysis">
                        <h3>AI Analysis</h3>
                        ${analysis}
                    </div>
                ` : ''}
            </div>
        `;
    }).join('\n<hr class="dream-divider">\n');

    return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Somnia.ai - Dream Journal Export</title>
    <style>
        @page {
            margin: 1in;
            size: letter;
        }
        
        body {
            font-family: Georgia, 'Times New Roman', serif;
            line-height: 1.6;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            color: #1E293B;
        }
        
        .header {
            text-align: center;
            margin-bottom: 40px;
            border-bottom: 2px solid #6366F1;
            padding-bottom: 20px;
        }
        
        .header h1 {
            font-size: 28px;
            margin-bottom: 5px;
            color: #6366F1;
        }
        
        .header p {
            color: #64748B;
            font-size: 14px;
        }
        
        .dream-entry {
            margin-bottom: 30px;
            page-break-inside: avoid;
        }
        
        .dream-header h2 {
            font-size: 20px;
            margin-bottom: 5px;
            color: #0F172A;
        }
        
        .dream-header .date {
            font-size: 12px;
            color: #64748B;
            margin: 5px 0;
        }
        
        .dream-header .quality {
            font-size: 14px;
            color: #6366F1;
        }
        
        .dream-header .tags {
            font-size: 12px;
            color: #818CF8;
        }
        
        .dream-content h3,
        .dream-analysis h3 {
            font-size: 14px;
            text-transform: uppercase;
            letter-spacing: 1px;
            color: #475569;
            border-bottom: 1px solid #E2E8F0;
            padding-bottom: 5px;
            margin-top: 15px;
        }
        
        .dream-analysis h4 {
            font-size: 14px;
            color: #6366F1;
            margin: 10px 0 5px;
        }
        
        .dream-divider {
            border: none;
            border-top: 1px dashed #CBD5E1;
            margin: 30px 0;
        }
        
        @media print {
            body { padding: 0; }
            .dream-entry { page-break-inside: avoid; }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Somnia Dream Journal</h1>
        <p>Exported from Somnia.ai • ${new Date().toLocaleDateString()}</p>
        <p>${dreams.length} dream${dreams.length !== 1 ? 's' : ''} recorded</p>
    </div>
    
    ${dreamEntries}
    
    <div style="text-align: center; margin-top: 40px; color: #94A3B8; font-size: 12px;">
        <p>Generated by Somnia.ai - Intelligent Dream Journal</p>
    </div>
</body>
</html>
    `;
};

/**
 * Generates a printable HTML view of the dream journal and opens the print dialog.
 * Creates a beautiful, serif-formatted document suitable for physical archiving.
 * 
 * @param dreams - Array of dreams to include in the PDF/Print view
 */
export const exportDreamJournalToPDF = (dreams: Dream[]): void => {
    if (dreams.length === 0) {
        alert('No dreams to export. Record some dreams first!');
        return;
    }

    const html = generatePrintableHTML(dreams);
    const printWindow = window.open('', '_blank');

    if (printWindow) {
        printWindow.document.write(html);
        printWindow.document.close();

        // Auto-trigger print dialog after content loads
        printWindow.onload = () => {
            setTimeout(() => {
                printWindow.print();
            }, 500);
        };
    }
};

/**
 * Exports dreams as a JSON file for data backup and portability.
 * Filename includes the current date (e.g., somnia-dreams-2024-01-01.json).
 * 
 * @param dreams - Array of dreams to export
 */
export const exportDreamsAsJSON = (dreams: Dream[]): void => {
    const data = JSON.stringify(dreams, null, 2);
    const blob = new Blob([data], { type: 'application/json' });
    const url = URL.createObjectURL(blob);

    const a = document.createElement('a');
    a.href = url;
    a.download = `somnia-dreams-${new Date().toISOString().split('T')[0]}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
};

/**
 * Imports dreams from a JSON backup file.
 * Automatically re-assigns IDs to prevent collisions with existing dreams.
 * Validates the JSON structure before processing.
 * 
 * @param file - The JSON file selected by the user
 * @param existingDreams - Current dreams in state (used for ID generation)
 * @returns Promise<Dream[]> - Array of validated dreams with new unique IDs
 */
export const importDreamsFromJSON = (
    file: File,
    existingDreams: Dream[]
): Promise<Dream[]> => {
    return new Promise((resolve, reject) => {
        const reader = new FileReader();

        reader.onload = (e) => {
            try {
                const content = e.target?.result as string;
                const imported = JSON.parse(content) as Dream[];

                // Validate basic structure
                if (!Array.isArray(imported)) {
                    throw new Error('Invalid format: expected array of dreams');
                }

                // Get max existing ID to avoid collisions
                const maxExistingId = Math.max(0, ...existingDreams.map(d => d.id));

                // Re-assign IDs to avoid collisions
                const withNewIds = imported.map((dream, index) => ({
                    ...dream,
                    id: maxExistingId + index + 1
                }));

                resolve(withNewIds);
            } catch (error) {
                reject(new Error('Failed to parse JSON file'));
            }
        };

        reader.onerror = () => reject(new Error('Failed to read file'));
        reader.readAsText(file);
    });
};
