// services/exportService.ts
import { Dream } from '../types';
import { escapeHtml } from './validationService';

/**
 * Generates a printable HTML document for dream journal export
 */
const generatePrintableHTML = (dreams: Dream[]): string => {
    const dreamEntries = dreams.map(dream => {
        const date = new Date(dream.timestamp).toLocaleDateString('en-US', {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric'
        });

        const qualityStars = dream.sleepQuality
            ? '★'.repeat(dream.sleepQuality) + '☆'.repeat(5 - dream.sleepQuality)
            : 'Not rated';

        // SECURITY FIX: Escape all user-provided content to prevent XSS
        const escapedTitle = escapeHtml(dream.title || 'Untitled Dream');
        const escapedDreamText = escapeHtml(dream.dreamText);
        const tags = dream.tags?.length
            ? dream.tags.map(t => `#${escapeHtml(t)}`).join(' ')
            : '';

        const analysis = dream.aiAnalysis?.analysis
            .map(a => `<h4>${escapeHtml(a.title)}</h4><p>${escapeHtml(a.content)}</p>`)
            .join('') || '';

        return `
            <div class="dream-entry">
                <div class="dream-header">
                    <h2>${escapedTitle}</h2>
                    <p class="date">${date}</p>
                    <p class="quality">Sleep Quality: ${qualityStars}</p>
                    ${tags ? `<p class="tags">${tags}</p>` : ''}
                </div>
                <div class="dream-content">
                    <h3>Dream</h3>
                    <p>${escapedDreamText}</p>
                </div>
                ${analysis ? `
                    <div class="dream-analysis">
                        <h3>AI Analysis</h3>
                        ${analysis}
                    </div>
                ` : ''}
            </div>
        `;
    }).join('\n<hr class="dream-divider">\n');

    return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Somnia.ai - Dream Journal Export</title>
    <style>
        @page {
            margin: 1in;
            size: letter;
        }
        
        body {
            font-family: Georgia, 'Times New Roman', serif;
            line-height: 1.6;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            color: #1E293B;
        }
        
        .header {
            text-align: center;
            margin-bottom: 40px;
            border-bottom: 2px solid #6366F1;
            padding-bottom: 20px;
        }
        
        .header h1 {
            font-size: 28px;
            margin-bottom: 5px;
            color: #6366F1;
        }
        
        .header p {
            color: #64748B;
            font-size: 14px;
        }
        
        .dream-entry {
            margin-bottom: 30px;
            page-break-inside: avoid;
        }
        
        .dream-header h2 {
            font-size: 20px;
            margin-bottom: 5px;
            color: #0F172A;
        }
        
        .dream-header .date {
            font-size: 12px;
            color: #64748B;
            margin: 5px 0;
        }
        
        .dream-header .quality {
            font-size: 14px;
            color: #6366F1;
        }
        
        .dream-header .tags {
            font-size: 12px;
            color: #818CF8;
        }
        
        .dream-content h3,
        .dream-analysis h3 {
            font-size: 14px;
            text-transform: uppercase;
            letter-spacing: 1px;
            color: #475569;
            border-bottom: 1px solid #E2E8F0;
            padding-bottom: 5px;
            margin-top: 15px;
        }
        
        .dream-analysis h4 {
            font-size: 14px;
            color: #6366F1;
            margin: 10px 0 5px;
        }
        
        .dream-divider {
            border: none;
            border-top: 1px dashed #CBD5E1;
            margin: 30px 0;
        }
        
        @media print {
            body { padding: 0; }
            .dream-entry { page-break-inside: avoid; }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Somnia Dream Journal</h1>
        <p>Exported from Somnia.ai • ${new Date().toLocaleDateString()}</p>
        <p>${dreams.length} dream${dreams.length !== 1 ? 's' : ''} recorded</p>
    </div>
    
    ${dreamEntries}
    
    <div style="text-align: center; margin-top: 40px; color: #94A3B8; font-size: 12px;">
        <p>Generated by Somnia.ai - Intelligent Dream Journal</p>
    </div>
</body>
</html>
    `;
};

/**
 * Generates a printable HTML view of the dream journal and opens the print dialog.
 * Creates a beautiful, serif-formatted document suitable for physical archiving.
 * 
 * @param dreams - Array of dreams to include in the PDF/Print view
 */
export const exportDreamJournalToPDF = (dreams: Dream[]): void => {
    if (dreams.length === 0) {
        alert('No dreams to export. Record some dreams first!');
        return;
    }

    const html = generatePrintableHTML(dreams);
    const printWindow = window.open('', '_blank');

    if (printWindow) {
        printWindow.document.write(html);
        printWindow.document.close();

        // Auto-trigger print dialog after content loads
        printWindow.onload = () => {
            setTimeout(() => {
                printWindow.print();
            }, 500);
        };
    }
};

/**
 * Exports dreams as a JSON file for data backup and portability.
 * Filename includes the current date (e.g., somnia-dreams-2024-01-01.json).
 * 
 * @param dreams - Array of dreams to export
 */
export const exportDreamsAsJSON = (dreams: Dream[]): void => {
    const data = JSON.stringify(dreams, null, 2);
    const blob = new Blob([data], { type: 'application/json' });
    const url = URL.createObjectURL(blob);

    const a = document.createElement('a');
    a.href = url;
    a.download = `somnia-dreams-${new Date().toISOString().split('T')[0]}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
};

/**
 * SECURITY FIX: Validate imported dream object against expected schema
 * Only allows known Dream properties, strips arbitrary data
 */
const validateDreamSchema = (obj: unknown, newId: number): Dream | null => {
    if (!obj || typeof obj !== 'object') return null;

    const raw = obj as Record<string, unknown>;

    // Validate required fields exist and have correct types
    if (typeof raw.dreamText !== 'string' || raw.dreamText.length === 0) return null;
    if (typeof raw.timestamp !== 'string') return null;

    // Construct clean Dream object with only valid properties
    const validDream: Dream = {
        id: newId,
        timestamp: raw.timestamp as string,
        dreamText: raw.dreamText as string,
        title: typeof raw.title === 'string' ? raw.title : 'Untitled Dream',
        sleepQuality: typeof raw.sleepQuality === 'number' && raw.sleepQuality >= 1 && raw.sleepQuality <= 5
            ? raw.sleepQuality : null,
        imageUrl: typeof raw.imageUrl === 'string' ? raw.imageUrl : null,
        aiAnalysis: raw.aiAnalysis && typeof raw.aiAnalysis === 'object' ? raw.aiAnalysis as Dream['aiAnalysis'] : null,
        chatHistory: Array.isArray(raw.chatHistory) ? raw.chatHistory : [],
        sleepAids: raw.sleepAids && typeof raw.sleepAids === 'object' ? raw.sleepAids as Dream['sleepAids'] : undefined,
        mood: typeof raw.mood === 'string' ? raw.mood as Dream['mood'] : undefined,
        tags: Array.isArray(raw.tags) ? raw.tags.filter((t): t is string => typeof t === 'string') : undefined,
    };

    return validDream;
};

/**
 * Imports dreams from a JSON backup file.
 * Automatically re-assigns IDs to prevent collisions with existing dreams.
 * Validates the JSON structure before processing.
 *
 * @param file - The JSON file selected by the user
 * @param existingDreams - Current dreams in state (used for ID generation)
 * @returns Promise<Dream[]> - Array of validated dreams with new unique IDs
 */
export const importDreamsFromJSON = (
    file: File,
    existingDreams: Dream[]
): Promise<Dream[]> => {
    return new Promise((resolve, reject) => {
        const reader = new FileReader();

        reader.onload = (e) => {
            try {
                const content = e.target?.result as string;
                const parsed = JSON.parse(content);

                // Support both versioned format { version, dreams } and raw array
                let imported: unknown[];
                if (Array.isArray(parsed)) {
                    imported = parsed;
                } else if (parsed && Array.isArray(parsed.dreams)) {
                    imported = parsed.dreams;
                } else {
                    throw new Error('Invalid format: expected array of dreams or { version, dreams }');
                }

                // Get max existing ID to avoid collisions
                const maxExistingId = Math.max(0, ...existingDreams.map(d => d.id));

                // SECURITY FIX: Validate each dream against schema instead of spreading
                const validDreams: Dream[] = [];
                imported.forEach((dream, index) => {
                    const validated = validateDreamSchema(dream, maxExistingId + index + 1);
                    if (validated) {
                        validDreams.push(validated);
                    }
                });

                if (validDreams.length === 0 && imported.length > 0) {
                    throw new Error('No valid dreams found in import file');
                }

                resolve(validDreams);
            } catch (error) {
                reject(new Error('Failed to parse JSON file'));
            }
        };

        reader.onerror = () => reject(new Error('Failed to read file'));
        reader.readAsText(file);
    });
};

/**
 * Exports dreams as an encrypted JSON file.
 * Helper that prompts the user for a password before exporting.
 */
import { encryptDataWithPassword, decryptDataWithPassword } from './securityService';

export const exportDreamsEncrypted = async (dreams: Dream[]): Promise<void> => {
    const password = prompt("Set a password for this encrypted backup:");
    if (!password) return; // User cancelled

    const data = JSON.stringify(dreams);
    const { encrypted, iv, salt } = await encryptDataWithPassword(data, password);

    const backupPayload = {
        version: 1,
        type: 'somnia-encrypted',
        payload: encrypted,
        iv,
        salt
    };

    const blob = new Blob([JSON.stringify(backupPayload, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);

    const a = document.createElement('a');
    a.href = url;
    a.download = `somnia-secure-backup-${new Date().toISOString().split('T')[0]}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
};

export const importDreamsEncrypted = async (
    file: File,
    existingDreams: Dream[]
): Promise<Dream[]> => {
    return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = async (e) => {
            try {
                const content = e.target?.result as string;
                const json = JSON.parse(content);

                if (json.type !== 'somnia-encrypted') {
                    // Fallback to normal import if not encrypted
                    if (Array.isArray(json)) return resolve(importDreamsFromJSON(file, existingDreams));
                    throw new Error('Invalid file format. Expected Somnia Encrypted Backup.');
                }

                const password = prompt("Enter password to decrypt backup:");
                if (!password) throw new Error("Password required");

                const decryptedJson = await decryptDataWithPassword(json.payload, json.iv, json.salt, password);
                const importedDreams = JSON.parse(decryptedJson) as Dream[];

                // Get max existing ID to avoid collisions
                const maxExistingId = Math.max(0, ...existingDreams.map((d: Dream) => d.id));

                // Re-assign IDs to avoid collisions
                const withNewIds = importedDreams.map((dream: Dream, index: number) => ({
                    ...dream,
                    id: maxExistingId + index + 1
                }));

                resolve(withNewIds);

            } catch (err) {
                console.error(err);
                reject(err);
            }
        };
        reader.onerror = () => reject(new Error("Failed to read file"));
        reader.readAsText(file);
    });
};



