// services/exportService.ts
/**
 * Dream journal export service - supports PDF, JSON, and encrypted backups
 *
 * I18N NOTES:
 * This file contains hardcoded 'en-US' locale for date formatting in exports.
 * When implementing full i18n:
 * - Use getUserLocale() from i18nUtils.ts instead of hardcoded 'en-US'
 * - Translate static strings like "Dream", "Sleep Quality:", "Exported from Somnia.ai"
 * - Consider adding locale to export metadata for re-import
 *
 * HARDCODED STRINGS requiring translation:
 * - "Untitled Dream" (default dream title)
 * - "Not rated" (no sleep quality)
 * - "Dream", "AI Analysis", "Sleep Quality:"
 * - "Somnia Dream Journal", "Exported from Somnia.ai"
 * - "Generated by Somnia.ai - Intelligent Dream Journal"
 * - Error messages: "No dreams to export...", "Failed to share..."
 *
 * DATE FORMATTING:
 * - Line 16: toLocaleDateString('en-US', ...) - should use user locale
 * - Line 158: toLocaleDateString() - uses browser locale (OK)
 * - Line 176: toLocaleDateString() - uses browser locale (OK)
 * - Line 179: toLocaleDateString('en-US', ...) - should use user locale
 */
import { Capacitor } from '@capacitor/core';
import { Share } from '@capacitor/share';
import { Filesystem, Directory, Encoding } from '@capacitor/filesystem';
import { Dream } from '../types';
import { escapeHtml } from './validationService';
import { logger } from './logger';

/**
 * Data shape for insights summary PDF export
 */
export interface InsightsSummaryData {
    totalDreams: number;
    currentStreak: number;
    bestStreak: number;
    avgSleepQuality: number;
    level: number;
    topThemes: string[];
    topMoods: string[];
    dreamFrequency: string;
    dateRange: string;
}

const isNative = Capacitor.isNativePlatform();

/**
 * Generates a printable HTML document for dream journal export
 */
const generatePrintableHTML = (dreams: Dream[]): string => {
    const dreamEntries = dreams.map(dream => {
        const date = new Date(dream.timestamp).toLocaleDateString('en-US', {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric'
        });

        const qualityStars = dream.sleepQuality
            ? '★'.repeat(dream.sleepQuality) + '☆'.repeat(5 - dream.sleepQuality)
            : 'Not rated';

        // SECURITY FIX: Escape all user-provided content to prevent XSS
        const escapedTitle = escapeHtml(dream.title || 'Untitled Dream');
        const escapedDreamText = escapeHtml(dream.dreamText);
        const tags = dream.tags?.length
            ? dream.tags.map(t => `#${escapeHtml(t)}`).join(' ')
            : '';

        const analysis = dream.aiAnalysis?.analysis
            .map(a => `<h4>${escapeHtml(a.title)}</h4><p>${escapeHtml(a.content)}</p>`)
            .join('') || '';

        return `
            <div class="dream-entry">
                <div class="dream-header">
                    <h2>${escapedTitle}</h2>
                    <p class="date">${date}</p>
                    <p class="quality">Sleep Quality: ${qualityStars}</p>
                    ${tags ? `<p class="tags">${tags}</p>` : ''}
                </div>
                <div class="dream-content">
                    <h3>Dream</h3>
                    <p>${escapedDreamText}</p>
                </div>
                ${analysis ? `
                    <div class="dream-analysis">
                        <h3>AI Analysis</h3>
                        ${analysis}
                    </div>
                ` : ''}
            </div>
        `;
    }).join('\n<hr class="dream-divider">\n');

    return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Somnia.ai - Dream Journal Export</title>
    <style>
        @page {
            margin: 1in;
            size: letter;
        }

        body {
            font-family: Georgia, 'Times New Roman', serif;
            line-height: 1.6;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            color: #1E293B;
        }

        .header {
            text-align: center;
            margin-bottom: 40px;
            border-bottom: 2px solid #6366F1;
            padding-bottom: 20px;
        }

        .header h1 {
            font-size: 28px;
            margin-bottom: 5px;
            color: #6366F1;
        }

        .header p {
            color: #64748B;
            font-size: 14px;
        }

        .dream-entry {
            margin-bottom: 30px;
            page-break-inside: avoid;
        }

        .dream-header h2 {
            font-size: 20px;
            margin-bottom: 5px;
            color: #0F172A;
        }

        .dream-header .date {
            font-size: 12px;
            color: #64748B;
            margin: 5px 0;
        }

        .dream-header .quality {
            font-size: 14px;
            color: #6366F1;
        }

        .dream-header .tags {
            font-size: 12px;
            color: #818CF8;
        }

        .dream-content h3,
        .dream-analysis h3 {
            font-size: 14px;
            text-transform: uppercase;
            letter-spacing: 1px;
            color: #475569;
            border-bottom: 1px solid #E2E8F0;
            padding-bottom: 5px;
            margin-top: 15px;
        }

        .dream-analysis h4 {
            font-size: 14px;
            color: #6366F1;
            margin: 10px 0 5px;
        }

        .dream-divider {
            border: none;
            border-top: 1px dashed #CBD5E1;
            margin: 30px 0;
        }

        @media print {
            body { padding: 0; }
            .dream-entry { page-break-inside: avoid; }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Somnia Dream Journal</h1>
        <p>Exported from Somnia.ai • ${new Date().toLocaleDateString()}</p>
        <p>${dreams.length} dream${dreams.length !== 1 ? 's' : ''} recorded</p>
    </div>

    ${dreamEntries}

    <div style="text-align: center; margin-top: 40px; color: #94A3B8; font-size: 12px;">
        <p>Generated by Somnia.ai - Intelligent Dream Journal</p>
    </div>
</body>
</html>
    `;
};

/**
 * Generates a plain text version for sharing
 */
const generatePlainText = (dreams: Dream[]): string => {
    const lines = ['SOMNIA DREAM JOURNAL', `Exported: ${new Date().toLocaleDateString()}`, `${dreams.length} dreams`, '', '---', ''];

    for (const dream of dreams) {
        const date = new Date(dream.timestamp).toLocaleDateString('en-US', {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric'
        });

        lines.push(dream.title || 'Untitled Dream');
        lines.push(date);
        if (dream.sleepQuality) {
            lines.push(`Sleep Quality: ${'★'.repeat(dream.sleepQuality)}${'☆'.repeat(5 - dream.sleepQuality)}`);
        }
        if (dream.tags?.length) {
            lines.push(`Tags: ${dream.tags.map(t => `#${t}`).join(' ')}`);
        }
        lines.push('');
        lines.push(dream.dreamText);
        lines.push('');
        lines.push('---');
        lines.push('');
    }

    return lines.join('\n');
};

/**
 * Export dream journal - uses native sharing on mobile, print dialog on web
 *
 * @param dreams - Array of dreams to include in the export
 */
export const exportDreamJournalToPDF = async (dreams: Dream[]): Promise<void> => {
    if (dreams.length === 0) {
        throw new Error('No dreams to export. Record some dreams first!');
    }

    if (isNative) {
        // On mobile, share as text since we can't do PDF generation natively
        const text = generatePlainText(dreams);

        try {
            await Share.share({
                title: 'Somnia Dream Journal',
                text: text,
                dialogTitle: 'Share Dream Journal',
            });
        } catch (e) {
            logger.error('[ExportService] Share failed:', e);
            throw new Error('Failed to share dream journal');
        }
    } else {
        // On web, use print dialog
        const html = generatePrintableHTML(dreams);
        const printWindow = window.open('', '_blank');

        if (printWindow) {
            printWindow.document.write(html);
            printWindow.document.close();

            // Auto-trigger print dialog after content loads
            printWindow.onload = () => {
                setTimeout(() => {
                    printWindow.print();
                }, 500);
            };
        }
    }
};

/**
 * Exports dreams as a JSON file for data backup and portability.
 * On mobile, shares the file. On web, downloads it.
 *
 * @param dreams - Array of dreams to export
 */
export const exportDreamsAsJSON = async (dreams: Dream[]): Promise<void> => {
    const data = JSON.stringify(dreams, null, 2);
    const filename = `somnia-dreams-${new Date().toISOString().split('T')[0]}.json`;

    if (isNative) {
        try {
            // Write to cache directory first
            const result = await Filesystem.writeFile({
                path: filename,
                data: data,
                directory: Directory.Cache,
                encoding: Encoding.UTF8,
            });

            // Share the file
            await Share.share({
                title: 'Somnia Dream Backup',
                url: result.uri,
                dialogTitle: 'Share Dream Backup',
            });
        } catch (e) {
            logger.error('[ExportService] Native export failed:', e);
            throw new Error('Failed to export dreams');
        }
    } else {
        // Web: download file
        const blob = new Blob([data], { type: 'application/json' });
        const url = URL.createObjectURL(blob);

        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }
};

/**
 * SECURITY FIX: Validate imported dream object against expected schema
 * Only allows known Dream properties, strips arbitrary data
 */
const validateDreamSchema = (obj: unknown, newId: number): Dream | null => {
    if (!obj || typeof obj !== 'object') return null;

    const raw = obj as Record<string, unknown>;

    // Validate required fields exist and have correct types
    if (typeof raw.dreamText !== 'string' || raw.dreamText.length === 0) return null;
    if (typeof raw.timestamp !== 'string') return null;

    // Construct clean Dream object with only valid properties
    const validDream: Dream = {
        id: newId,
        timestamp: raw.timestamp as string,
        dreamText: raw.dreamText as string,
        title: typeof raw.title === 'string' ? raw.title : 'Untitled Dream',
        sleepQuality: typeof raw.sleepQuality === 'number' && raw.sleepQuality >= 1 && raw.sleepQuality <= 5
            ? raw.sleepQuality : null,
        imageUrl: typeof raw.imageUrl === 'string' ? raw.imageUrl : null,
        aiAnalysis: raw.aiAnalysis && typeof raw.aiAnalysis === 'object' ? raw.aiAnalysis as Dream['aiAnalysis'] : null,
        chatHistory: Array.isArray(raw.chatHistory) ? raw.chatHistory : [],
        sleepAids: raw.sleepAids && typeof raw.sleepAids === 'object' ? raw.sleepAids as Dream['sleepAids'] : undefined,
        mood: typeof raw.mood === 'string' ? raw.mood as Dream['mood'] : undefined,
        tags: Array.isArray(raw.tags) ? raw.tags.filter((t): t is string => typeof t === 'string') : undefined,
    };

    return validDream;
};

// SECURITY FIX: Maximum file size for imports (10MB)
const MAX_IMPORT_FILE_SIZE = 10 * 1024 * 1024;

/**
 * Imports dreams from a JSON backup file.
 * Automatically re-assigns IDs to prevent collisions with existing dreams.
 * Validates the JSON structure before processing.
 *
 * @param file - The JSON file selected by the user
 * @param existingDreams - Current dreams in state (used for ID generation)
 * @returns Promise<Dream[]> - Array of validated dreams with new unique IDs
 */
export const importDreamsFromJSON = (
    file: File,
    existingDreams: Dream[]
): Promise<Dream[]> => {
    return new Promise((resolve, reject) => {
        // SECURITY FIX: Check file size before processing
        if (file.size > MAX_IMPORT_FILE_SIZE) {
            reject(new Error(`File too large. Maximum size is ${MAX_IMPORT_FILE_SIZE / 1024 / 1024}MB`));
            return;
        }

        const reader = new FileReader();

        reader.onload = (e) => {
            try {
                const content = e.target?.result as string;
                const parsed = JSON.parse(content);

                // Support both versioned format { version, dreams } and raw array
                let imported: unknown[];
                if (Array.isArray(parsed)) {
                    imported = parsed;
                } else if (parsed && Array.isArray(parsed.dreams)) {
                    imported = parsed.dreams;
                } else {
                    throw new Error('Invalid format: expected array of dreams or { version, dreams }');
                }

                // Get max existing ID to avoid collisions
                const maxExistingId = Math.max(0, ...existingDreams.map(d => d.id));

                // SECURITY FIX: Validate each dream against schema instead of spreading
                const validDreams: Dream[] = [];
                imported.forEach((dream, index) => {
                    const validated = validateDreamSchema(dream, maxExistingId + index + 1);
                    if (validated) {
                        validDreams.push(validated);
                    }
                });

                if (validDreams.length === 0 && imported.length > 0) {
                    throw new Error('No valid dreams found in import file');
                }

                resolve(validDreams);
            } catch (_error) {
                reject(new Error('Failed to parse JSON file'));
            }
        };

        reader.onerror = () => reject(new Error('Failed to read file'));
        reader.readAsText(file);
    });
};

/**
 * Exports dreams as an encrypted JSON file.
 * SECURITY FIX: Now accepts password as parameter instead of using prompt()
 * The calling component should use PasswordInputModal to collect the password securely
 */
import { encryptDataWithPassword, decryptDataWithPassword } from './securityService';

export const exportDreamsEncrypted = async (dreams: Dream[], password: string): Promise<void> => {
    if (!password) {
        throw new Error('Password is required for encrypted export');
    }

    const dreamsData = JSON.stringify(dreams);
    const { encrypted, iv, salt } = await encryptDataWithPassword(dreamsData, password);

    const backupPayload = {
        version: 1,
        type: 'somnia-encrypted',
        payload: encrypted,
        iv,
        salt
    };

    const data = JSON.stringify(backupPayload, null, 2);
    const filename = `somnia-secure-backup-${new Date().toISOString().split('T')[0]}.json`;

    if (isNative) {
        try {
            // Write to cache directory first
            const result = await Filesystem.writeFile({
                path: filename,
                data: data,
                directory: Directory.Cache,
                encoding: Encoding.UTF8,
            });

            // Share the file
            await Share.share({
                title: 'Somnia Encrypted Backup',
                url: result.uri,
                dialogTitle: 'Share Encrypted Backup',
            });
        } catch (e) {
            logger.error('[ExportService] Native encrypted export failed:', e);
            throw new Error('Failed to export encrypted backup');
        }
    } else {
        // Web: download file
        const blob = new Blob([data], { type: 'application/json' });
        const url = URL.createObjectURL(blob);

        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }
};

/**
 * Checks if a file is an encrypted Somnia backup
 * Used to determine which password mode to show
 */
export const isEncryptedBackup = async (file: File): Promise<boolean> => {
    return new Promise((resolve) => {
        const reader = new FileReader();
        reader.onload = (e) => {
            try {
                const content = e.target?.result as string;
                const json = JSON.parse(content);
                resolve(json.type === 'somnia-encrypted');
            } catch {
                resolve(false);
            }
        };
        reader.onerror = () => resolve(false);
        reader.readAsText(file);
    });
};

/**
 * Imports dreams from an encrypted backup file.
 * SECURITY FIX: Now accepts password as parameter instead of using prompt()
 * The calling component should use PasswordInputModal to collect the password securely
 */
export const importDreamsEncrypted = async (
    file: File,
    existingDreams: Dream[],
    password: string
): Promise<Dream[]> => {
    return new Promise((resolve, reject) => {
        // SECURITY FIX: Check file size before processing
        if (file.size > MAX_IMPORT_FILE_SIZE) {
            reject(new Error(`File too large. Maximum size is ${MAX_IMPORT_FILE_SIZE / 1024 / 1024}MB`));
            return;
        }

        if (!password) {
            reject(new Error('Password is required for encrypted import'));
            return;
        }

        const reader = new FileReader();
        reader.onload = async (e) => {
            try {
                const content = e.target?.result as string;
                const json = JSON.parse(content);

                if (json.type !== 'somnia-encrypted') {
                    // Fallback to normal import if not encrypted
                    if (Array.isArray(json)) return resolve(importDreamsFromJSON(file, existingDreams));
                    throw new Error('Invalid file format. Expected Somnia Encrypted Backup.');
                }

                const decryptedJson = await decryptDataWithPassword(json.payload, json.iv, json.salt, password);
                const importedDreams = JSON.parse(decryptedJson) as unknown[];

                // Get max existing ID to avoid collisions
                const maxExistingId = Math.max(0, ...existingDreams.map((d: Dream) => d.id));

                // SECURITY FIX: Validate each dream against schema
                const validDreams: Dream[] = [];
                importedDreams.forEach((dream, index) => {
                    const validated = validateDreamSchema(dream, maxExistingId + index + 1);
                    if (validated) {
                        validDreams.push(validated);
                    }
                });

                if (validDreams.length === 0 && importedDreams.length > 0) {
                    throw new Error('No valid dreams found in encrypted backup');
                }

                resolve(validDreams);

            } catch (err) {
                reject(err);
            }
        };
        reader.onerror = () => reject(new Error("Failed to read file"));
        reader.readAsText(file);
    });
};

/**
 * Generates printable HTML for an insights summary
 */
const generateInsightsHTML = (data: InsightsSummaryData): string => {
    const themesHtml = data.topThemes.length > 0
        ? data.topThemes.map(t => `<li>${escapeHtml(t)}</li>`).join('\n')
        : '<li>No themes detected yet</li>';

    const moodsHtml = data.topMoods.length > 0
        ? data.topMoods.map(m => `<li>${escapeHtml(m)}</li>`).join('\n')
        : '<li>No mood data yet</li>';

    const qualityDisplay = data.avgSleepQuality > 0
        ? `${data.avgSleepQuality.toFixed(1)} / 5`
        : 'No ratings yet';

    return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Somnia Dream Insights</title>
    <style>
        @page {
            margin: 1in;
            size: letter;
        }

        body {
            font-family: Georgia, 'Times New Roman', serif;
            line-height: 1.6;
            max-width: 700px;
            margin: 0 auto;
            padding: 40px 20px;
            color: #1E293B;
        }

        .header {
            text-align: center;
            margin-bottom: 36px;
            border-bottom: 2px solid #6366F1;
            padding-bottom: 20px;
        }

        .header h1 {
            font-size: 28px;
            margin: 0 0 6px;
            color: #6366F1;
        }

        .header .date-range {
            font-size: 14px;
            color: #64748B;
            margin: 0;
        }

        .stats-grid {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 16px;
            margin-bottom: 32px;
        }

        .stat-card {
            text-align: center;
            padding: 16px 12px;
            border: 1px solid #E2E8F0;
            border-radius: 10px;
        }

        .stat-card .value {
            font-size: 28px;
            font-weight: bold;
            color: #6366F1;
            display: block;
        }

        .stat-card .label {
            font-size: 12px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            color: #64748B;
            margin-top: 4px;
        }

        .section {
            margin-bottom: 28px;
        }

        .section h2 {
            font-size: 18px;
            color: #0F172A;
            border-bottom: 1px solid #E2E8F0;
            padding-bottom: 6px;
            margin-bottom: 12px;
        }

        .section ul {
            padding-left: 20px;
            margin: 0;
        }

        .section li {
            margin-bottom: 6px;
            color: #334155;
        }

        .frequency {
            font-size: 15px;
            color: #475569;
            padding: 12px 16px;
            background: #F8FAFC;
            border-radius: 8px;
            border-left: 3px solid #6366F1;
        }

        .footer {
            text-align: center;
            margin-top: 40px;
            padding-top: 16px;
            border-top: 1px solid #E2E8F0;
            color: #94A3B8;
            font-size: 12px;
        }

        @media print {
            body { padding: 0; }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Somnia Dream Insights</h1>
        <p class="date-range">${escapeHtml(data.dateRange)}</p>
    </div>

    <div class="stats-grid">
        <div class="stat-card">
            <span class="value">${data.totalDreams}</span>
            <span class="label">Total Dreams</span>
        </div>
        <div class="stat-card">
            <span class="value">${data.currentStreak}</span>
            <span class="label">Current Streak</span>
        </div>
        <div class="stat-card">
            <span class="value">${data.bestStreak}</span>
            <span class="label">Best Streak</span>
        </div>
        <div class="stat-card">
            <span class="value">${qualityDisplay}</span>
            <span class="label">Avg Sleep Quality</span>
        </div>
        <div class="stat-card">
            <span class="value">${data.level}</span>
            <span class="label">Level</span>
        </div>
        <div class="stat-card">
            <span class="value">${escapeHtml(data.dreamFrequency)}</span>
            <span class="label">Frequency</span>
        </div>
    </div>

    <div class="section">
        <h2>Top Themes</h2>
        <ul>
            ${themesHtml}
        </ul>
    </div>

    <div class="section">
        <h2>Top Moods</h2>
        <ul>
            ${moodsHtml}
        </ul>
    </div>

    <div class="footer">
        <p>Generated by Somnia &mdash; somnia.ai</p>
    </div>
</body>
</html>
    `;
};

/**
 * Generates a plain-text version of the insights summary for native sharing
 */
const generateInsightsPlainText = (data: InsightsSummaryData): string => {
    const qualityDisplay = data.avgSleepQuality > 0
        ? `${data.avgSleepQuality.toFixed(1)} / 5`
        : 'No ratings yet';

    const lines = [
        'SOMNIA DREAM INSIGHTS',
        data.dateRange,
        '',
        '--- STATS ---',
        `Total Dreams: ${data.totalDreams}`,
        `Current Streak: ${data.currentStreak}`,
        `Best Streak: ${data.bestStreak}`,
        `Avg Sleep Quality: ${qualityDisplay}`,
        `Level: ${data.level}`,
        `Frequency: ${data.dreamFrequency}`,
        '',
        '--- TOP THEMES ---',
        ...(data.topThemes.length > 0
            ? data.topThemes.map(t => `  - ${t}`)
            : ['  No themes detected yet']),
        '',
        '--- TOP MOODS ---',
        ...(data.topMoods.length > 0
            ? data.topMoods.map(m => `  - ${m}`)
            : ['  No mood data yet']),
        '',
        'Generated by Somnia - somnia.ai',
    ];

    return lines.join('\n');
};

/**
 * Export insights summary - uses native sharing on mobile, print dialog on web
 */
export const exportInsightsSummary = async (data: InsightsSummaryData): Promise<void> => {
    if (isNative) {
        const text = generateInsightsPlainText(data);

        try {
            await Share.share({
                title: 'Somnia Dream Insights',
                text: text,
                dialogTitle: 'Share Dream Insights',
            });
        } catch (e) {
            logger.error('[ExportService] Share insights failed:', e);
            throw new Error('Failed to share insights summary');
        }
    } else {
        const html = generateInsightsHTML(data);
        const printWindow = window.open('', '_blank');

        if (printWindow) {
            printWindow.document.write(html);
            printWindow.document.close();

            printWindow.onload = () => {
                setTimeout(() => {
                    printWindow.print();
                }, 500);
            };
        }
    }
};
